version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: Constanta
      POSTGRES_PASSWORD: Constanta
      POSTGRES_DB: Constanta
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: go
    build:
      context: .
    depends_on:
      - "postgres"
