version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: constanta
      POSTGRES_PASSWORD: constanta
      POSTGRES_DB: constanta
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: go
    ports:
      - "8001:8001"
    build:
      context: .
    depends_on:
      - "postgres"

volumes:
  dbdata:
